apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector-deployment
  labels:
    app: detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detector
  template:
    metadata:
      labels:
        app: detector 
    spec:
      containers:
      - name: detector
        image: jorgevasquezutec/cloud-detector
        ports:
        - containerPort: 3003
        env:
        - name: BROKERS
          value: "one-node-cluster.redpanda:9092"
        - name: ENV
          value: "production"
        - name: HOSTNAME_SERVER
          value: "server-service"

