apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: detector-scaled
spec:
  scaleTargetRef:
    name: detector #(1)
  cooldownPeriod: 30 # (2)
  maxReplicaCount:  5 # (3)
  minReplicaCount:  1
  advanced:
    horizontalPodAutoscalerConfig: # (4)
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Percent
              value: 50
              periodSeconds: 300
  triggers: # (5)
    - type: kafka
      metadata:
        bootstrapServers: one-node-cluster.redpanda:9092
        consumerGroup: auth
        topic: filtered
        lagThreshold: '5'